### PR TITLE
Empty pointValues array on draw

### PR DESCRIPTION
**Pull request by Zertz**
This prevents the array from growing indefinitely when the window is resized

### CODE REVIEW

**Comment by Zertz** [comment]
@ant7 First of all, thanks for your time merging my other PR's! :)

Do you see any issues with this one? Currently, the plugin works on initial at page load at whichever viewport size but when the browser's window is resized, point values are added without clearing the ones from the previous draw event causing this array to grow indefinitely which in turn breaks the algorithm attempting to find the closest point value.

**Comment by ant7** [comment]
Hi @Zertz,

Thank you for your contributions. It's nice to see that people are interested in this repository :)
Sorry for missing this request. I just didn't had the time to test the changes, but I'll try to do that by the end of the week and merge then.

Thank you
All the best

**Comment by Zertz** [comment]
@ant7 Hey! Sorry to bother you, have you had time to look into this?

**Comment by ant7** [comment]
Hi @Zertz ,

Sorry for not getting back to you sooner. I didn't merged this yet, as I wasn't able to reproduce the issue it resolves. Can you send me a demo and some directions to reproduce the issue?

Thank you
All the best

**Pull request closed without merging**
